### ISSUE TITLE
Error installing plugin

### ISSUE THREAD

**Issue by dwoodman2008** [benbalter/wordpress-to-jekyll-exporter#281]
### Describe the bug

Plugin could not be activated because it triggered a fatal error.

Warning: require(/home/suauk/public_html/stamfordu3a.org.uk/wp-content/plugins/jekyll-exporter/vendor/composer/../myclabs/deep-copy/src/DeepCopy/deep_copy.php): failed to open stream: No such file or directory in /home/suauk/public_html/stamfordu3a.org.uk/wp-content/plugins/jekyll-exporter/vendor/composer/autoload_real.php on line 76

### Steps to reproduce the behavior

1. Running wordpress 5.9 php 7.4
2. Install plugin from WP directory ver 2.3.5
3. Activate
4. See error above

### Expected behavior
Plugin would activate as normal.

**Comment by benbalter** [comment]
@dwoodman2008 Thanks for opening the issue. I know what's going on and will work on a fix, likely released later today. In the interim, version `2.3.2` should not be affected by this regression.

**Comment by benbalter** [comment]
This should be fixed with [`2.3.6`](https://github.com/benbalter/wordpress-to-jekyll-exporter/releases/tag/2.3.6), and I added a new integration test to ensure the plugin will activate on a fresh WordPress install to ensure we can't introduce regressions like this going forward. Thanks again for the report.
