### ISSUE TITLE
Trying to export 'products' from woo commerce

### ISSUE THREAD

**Issue by adster101** [benbalter/wordpress-to-jekyll-exporter#72]
Firstly, I'm no WP expert but I would like to export content from WP to Jekyll.

I have a site with 16 or so products managed by the 'woo commerce' plugin. When I run the exporter these products are not exported (as far as I can tell) and adding 

add_filter( 'jekyll_export_post_types', array('posts', 'pages', 'product') );

to the theme's functions.php folder does not work. I get an empty _posts folder. 

Is it possible to extract these products as they are listed in the wp_posts table.

**Comment by blairmacintyre** [comment]
I'd be curious to get a bit of help on this too.  I'm not a PhP/WP expert either, and want to extract some "portfolio" fields from an old theme (prior to wordpress having a portfolio type).  I assume I need to add

add_filter( 'jekyll_export_post_types', array('posts', 'pages', 'portfolio') );

to something, based on the readme, but I haven't a clue where to add it!  (I know the post_type is "portfolio" since that's what it says in the XML if I do a full export of the site)

**Comment by adster101** [comment]
You can add it to your themes functions.php file.

I looked at the code and it seems as though the parts are pulled out of database but it fails to write them out to file.

Would be interested to hear Igor works for you.

**Comment by blairmacintyre** [comment]
Crashes after running for a while.  Here's a snapshot of the error.

![foo](https://cloud.githubusercontent.com/assets/1348861/12593594/da32504e-c43f-11e5-8fb6-5c1e619350ba.png)

**Comment by blairmacintyre** [comment]
Despite my lack of PhP experience, here's how to get it working.  First, I have no idea what to do with the suggestion of adding a filter.  So ignore that.

You need to do two things.

- on line 93  add your post type to the apply_filter.  I changed
```
     $post_types = apply_filters( 'jekyll_export_post_types', array( 'post', 'page' ) );
```
to
```
    $post_types = apply_filters( 'jekyll_export_post_types', array( 'post', 'page', 'portfolio' ) );
```

- after line 223, create the directory for your post type.  It needs to be the type + 's', so I added
```
    $wp_filesystem->mkdir( $this->dir . '_portfolios/' );
```

That's it.  Adding to the filter will include the posts, but they won't show up unless you create the directory, because down on line 297, they create the filename for the post as being post type + 's/' + the name based on the date and post_name.

**Comment by adster101** [comment]
Thanks blair, that works for me as well.

So there are two issues...

1/ Adding a customer filter doesn't seem to work (at least if it does the docs aren't clear)
2/ The custom folder isn't created as expected.

**Comment by blairmacintyre** [comment]
Right.  Changing the apply_filter was easy;  I don't know PhP well enough to do an iteration through the post_types and check (for each element that isn't "pages") if the directory exists, or to just make it.

Ideally, someone who knows PhP and Wordpress would add a simple control panel, where you could add post types, and have an "export" button.

**Comment by dylan-k** [comment]
I was also unsure where to add the line to include post types. Could the readme be updated to help clarify?
