### ISSUE TITLE
Plugin Exported non-UTF-8 Characters

### ISSUE THREAD

**Issue by thecapacity** [benbalter/wordpress-to-jekyll-exporter#78]
I'm still getting used to jekyll so it was really throwing me for a loop when things stopped building/updating.

Turns out there were nonUTF-8 characters in a few of my posts. I found them via:
- A Stackoverflow command (can't find the link): find . -type f | xargs -I {} bash -c "iconv -f utf-8 -t utf-16 {} &>/dev/null || echo {}"
- Converted them via (another SO guide): iconv -f utf-8 -t utf-8 -c $FILE_NAME > OK; MOVE OK $FILE_NAME

Might be relatively easy to add a UTF-8 convert/filter to exported files.

**Comment by aviflax** [comment]
Thanks for the helpful info!

I’m not great at shell stuff so I had a little trouble with the above commands; through a bunch of trial and error I managed to put together a script that worked for me:

```bash
files=`ls *.md | xargs -R 2 -I {} bash -c "iconv -f utf-8 -t utf-16 {} &>/dev/null || echo {}"`

for file in $files
do
  if [[ "$file" != "{}" ]]
  then
    echo $file
    iconv -f utf8 -t utf8 -c "$file" | sponge "$file"
  fi
done
```

(This should be invoked from within the dir `_posts` (if used as-is).)

Please note: the script uses the program [`sponge`](https://rentes.github.io/unix/utilities/2015/07/27/moreutils-package/#sponge). I installed it on my Mac via [Homebrew](http://brew.sh) by installing [`moreutils`](https://rentes.github.io/unix/utilities/2015/07/27/moreutils-package/) with `brew install moreutils`.

Of course I’d love to see this fixed in the tool itself 😉 but in the meantime I’m happy to share workarounds.
